// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controlmessage.proto

package control;

public final class Controlmessage {
  private Controlmessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ControlMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:control.ControlMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string origin = 1;</code>
     *
     * <pre>
     *&#47; Unique description of the origin of this event.
     * </pre>
     */
    boolean hasOrigin();
    /**
     * <code>required string origin = 1;</code>
     *
     * <pre>
     *&#47; Unique description of the origin of this event.
     * </pre>
     */
    String getOrigin();
    /**
     * <code>required string origin = 1;</code>
     *
     * <pre>
     *&#47; Unique description of the origin of this event.
     * </pre>
     */
    com.google.protobuf.ByteString
        getOriginBytes();

    /**
     * <code>required .control.UUID identifier = 2;</code>
     *
     * <pre>
     *&#47; A unique identifier for this control
     * </pre>
     */
    boolean hasIdentifier();
    /**
     * <code>required .control.UUID identifier = 2;</code>
     *
     * <pre>
     *&#47; A unique identifier for this control
     * </pre>
     */
    control.Uuid.UUID getIdentifier();
    /**
     * <code>required .control.UUID identifier = 2;</code>
     *
     * <pre>
     *&#47; A unique identifier for this control
     * </pre>
     */
    control.Uuid.UUIDOrBuilder getIdentifierOrBuilder();

    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this ControlMessage.
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this ControlMessage.
     * </pre>
     */
    long getTimestamp();

    /**
     * <code>required .control.ControlMessage.ControlType controlType = 4;</code>
     *
     * <pre>
     *&#47; Type of wrapped control. Only the optional field corresponding to the value of ControlType should be set.
     * </pre>
     */
    boolean hasControlType();
    /**
     * <code>required .control.ControlMessage.ControlType controlType = 4;</code>
     *
     * <pre>
     *&#47; Type of wrapped control. Only the optional field corresponding to the value of ControlType should be set.
     * </pre>
     */
    control.Controlmessage.ControlMessage.ControlType getControlType();

    /**
     * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
     */
    boolean hasHeartbeatRequest();
    /**
     * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
     */
    control.Heartbeatrequest.HeartbeatRequest getHeartbeatRequest();
    /**
     * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
     */
    control.Heartbeatrequest.HeartbeatRequestOrBuilder getHeartbeatRequestOrBuilder();
  }
  /**
   * Protobuf type {@code control.ControlMessage}
   *
   * <pre>
   *&#47; ControlMessage wraps a control command and adds metadata.
   * </pre>
   */
  public static final class ControlMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:control.ControlMessage)
      ControlMessageOrBuilder {
    // Use ControlMessage.newBuilder() to construct.
    private ControlMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ControlMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ControlMessage defaultInstance;
    public static ControlMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ControlMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ControlMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              origin_ = bs;
              break;
            }
            case 18: {
              control.Uuid.UUID.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = identifier_.toBuilder();
              }
              identifier_ = input.readMessage(control.Uuid.UUID.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(identifier_);
                identifier_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              control.Controlmessage.ControlMessage.ControlType value = control.Controlmessage.ControlMessage.ControlType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                controlType_ = value;
              }
              break;
            }
            case 42: {
              control.Heartbeatrequest.HeartbeatRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = heartbeatRequest_.toBuilder();
              }
              heartbeatRequest_ = input.readMessage(control.Heartbeatrequest.HeartbeatRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(heartbeatRequest_);
                heartbeatRequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return control.Controlmessage.internal_static_control_ControlMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return control.Controlmessage.internal_static_control_ControlMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              control.Controlmessage.ControlMessage.class, control.Controlmessage.ControlMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ControlMessage> PARSER =
        new com.google.protobuf.AbstractParser<ControlMessage>() {
      public ControlMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ControlMessage(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<ControlMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code control.ControlMessage.ControlType}
     *
     * <pre>
     *&#47; Type of the wrapped control.
     * </pre>
     */
    public enum ControlType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HeartbeatRequest = 1;</code>
       */
      HeartbeatRequest(0, 1),
      ;

      /**
       * <code>HeartbeatRequest = 1;</code>
       */
      public static final int HeartbeatRequest_VALUE = 1;


      public final int getNumber() { return value; }

      public static ControlType valueOf(int value) {
        switch (value) {
          case 1: return HeartbeatRequest;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ControlType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ControlType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ControlType>() {
              public ControlType findValueByNumber(int number) {
                return ControlType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return control.Controlmessage.ControlMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final ControlType[] VALUES = values();

      public static ControlType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ControlType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:control.ControlMessage.ControlType)
    }

    private int bitField0_;
    public static final int ORIGIN_FIELD_NUMBER = 1;
    private Object origin_;
    /**
     * <code>required string origin = 1;</code>
     *
     * <pre>
     *&#47; Unique description of the origin of this event.
     * </pre>
     */
    public boolean hasOrigin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string origin = 1;</code>
     *
     * <pre>
     *&#47; Unique description of the origin of this event.
     * </pre>
     */
    public String getOrigin() {
      Object ref = origin_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          origin_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string origin = 1;</code>
     *
     * <pre>
     *&#47; Unique description of the origin of this event.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOriginBytes() {
      Object ref = origin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        origin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDENTIFIER_FIELD_NUMBER = 2;
    private control.Uuid.UUID identifier_;
    /**
     * <code>required .control.UUID identifier = 2;</code>
     *
     * <pre>
     *&#47; A unique identifier for this control
     * </pre>
     */
    public boolean hasIdentifier() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .control.UUID identifier = 2;</code>
     *
     * <pre>
     *&#47; A unique identifier for this control
     * </pre>
     */
    public control.Uuid.UUID getIdentifier() {
      return identifier_;
    }
    /**
     * <code>required .control.UUID identifier = 2;</code>
     *
     * <pre>
     *&#47; A unique identifier for this control
     * </pre>
     */
    public control.Uuid.UUIDOrBuilder getIdentifierOrBuilder() {
      return identifier_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this ControlMessage.
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this ControlMessage.
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int CONTROLTYPE_FIELD_NUMBER = 4;
    private control.Controlmessage.ControlMessage.ControlType controlType_;
    /**
     * <code>required .control.ControlMessage.ControlType controlType = 4;</code>
     *
     * <pre>
     *&#47; Type of wrapped control. Only the optional field corresponding to the value of ControlType should be set.
     * </pre>
     */
    public boolean hasControlType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .control.ControlMessage.ControlType controlType = 4;</code>
     *
     * <pre>
     *&#47; Type of wrapped control. Only the optional field corresponding to the value of ControlType should be set.
     * </pre>
     */
    public control.Controlmessage.ControlMessage.ControlType getControlType() {
      return controlType_;
    }

    public static final int HEARTBEATREQUEST_FIELD_NUMBER = 5;
    private control.Heartbeatrequest.HeartbeatRequest heartbeatRequest_;
    /**
     * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
     */
    public boolean hasHeartbeatRequest() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
     */
    public control.Heartbeatrequest.HeartbeatRequest getHeartbeatRequest() {
      return heartbeatRequest_;
    }
    /**
     * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
     */
    public control.Heartbeatrequest.HeartbeatRequestOrBuilder getHeartbeatRequestOrBuilder() {
      return heartbeatRequest_;
    }

    private void initFields() {
      origin_ = "";
      identifier_ = control.Uuid.UUID.getDefaultInstance();
      timestamp_ = 0L;
      controlType_ = control.Controlmessage.ControlMessage.ControlType.HeartbeatRequest;
      heartbeatRequest_ = control.Heartbeatrequest.HeartbeatRequest.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOrigin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIdentifier()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasControlType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getIdentifier().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOriginBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, identifier_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, controlType_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, heartbeatRequest_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOriginBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, identifier_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, controlType_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, heartbeatRequest_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static control.Controlmessage.ControlMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static control.Controlmessage.ControlMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static control.Controlmessage.ControlMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static control.Controlmessage.ControlMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static control.Controlmessage.ControlMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static control.Controlmessage.ControlMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static control.Controlmessage.ControlMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static control.Controlmessage.ControlMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static control.Controlmessage.ControlMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static control.Controlmessage.ControlMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(control.Controlmessage.ControlMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code control.ControlMessage}
     *
     * <pre>
     *&#47; ControlMessage wraps a control command and adds metadata.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:control.ControlMessage)
        control.Controlmessage.ControlMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return control.Controlmessage.internal_static_control_ControlMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return control.Controlmessage.internal_static_control_ControlMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                control.Controlmessage.ControlMessage.class, control.Controlmessage.ControlMessage.Builder.class);
      }

      // Construct using control.Controlmessage.ControlMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIdentifierFieldBuilder();
          getHeartbeatRequestFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        origin_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (identifierBuilder_ == null) {
          identifier_ = control.Uuid.UUID.getDefaultInstance();
        } else {
          identifierBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        controlType_ = control.Controlmessage.ControlMessage.ControlType.HeartbeatRequest;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (heartbeatRequestBuilder_ == null) {
          heartbeatRequest_ = control.Heartbeatrequest.HeartbeatRequest.getDefaultInstance();
        } else {
          heartbeatRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return control.Controlmessage.internal_static_control_ControlMessage_descriptor;
      }

      public control.Controlmessage.ControlMessage getDefaultInstanceForType() {
        return control.Controlmessage.ControlMessage.getDefaultInstance();
      }

      public control.Controlmessage.ControlMessage build() {
        control.Controlmessage.ControlMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public control.Controlmessage.ControlMessage buildPartial() {
        control.Controlmessage.ControlMessage result = new control.Controlmessage.ControlMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.origin_ = origin_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (identifierBuilder_ == null) {
          result.identifier_ = identifier_;
        } else {
          result.identifier_ = identifierBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.controlType_ = controlType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (heartbeatRequestBuilder_ == null) {
          result.heartbeatRequest_ = heartbeatRequest_;
        } else {
          result.heartbeatRequest_ = heartbeatRequestBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof control.Controlmessage.ControlMessage) {
          return mergeFrom((control.Controlmessage.ControlMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(control.Controlmessage.ControlMessage other) {
        if (other == control.Controlmessage.ControlMessage.getDefaultInstance()) return this;
        if (other.hasOrigin()) {
          bitField0_ |= 0x00000001;
          origin_ = other.origin_;
          onChanged();
        }
        if (other.hasIdentifier()) {
          mergeIdentifier(other.getIdentifier());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasControlType()) {
          setControlType(other.getControlType());
        }
        if (other.hasHeartbeatRequest()) {
          mergeHeartbeatRequest(other.getHeartbeatRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOrigin()) {

          return false;
        }
        if (!hasIdentifier()) {

          return false;
        }
        if (!hasTimestamp()) {

          return false;
        }
        if (!hasControlType()) {

          return false;
        }
        if (!getIdentifier().isInitialized()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        control.Controlmessage.ControlMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (control.Controlmessage.ControlMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object origin_ = "";
      /**
       * <code>required string origin = 1;</code>
       *
       * <pre>
       *&#47; Unique description of the origin of this event.
       * </pre>
       */
      public boolean hasOrigin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string origin = 1;</code>
       *
       * <pre>
       *&#47; Unique description of the origin of this event.
       * </pre>
       */
      public String getOrigin() {
        Object ref = origin_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            origin_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string origin = 1;</code>
       *
       * <pre>
       *&#47; Unique description of the origin of this event.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOriginBytes() {
        Object ref = origin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          origin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string origin = 1;</code>
       *
       * <pre>
       *&#47; Unique description of the origin of this event.
       * </pre>
       */
      public Builder setOrigin(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        origin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string origin = 1;</code>
       *
       * <pre>
       *&#47; Unique description of the origin of this event.
       * </pre>
       */
      public Builder clearOrigin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        origin_ = getDefaultInstance().getOrigin();
        onChanged();
        return this;
      }
      /**
       * <code>required string origin = 1;</code>
       *
       * <pre>
       *&#47; Unique description of the origin of this event.
       * </pre>
       */
      public Builder setOriginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        origin_ = value;
        onChanged();
        return this;
      }

      private control.Uuid.UUID identifier_ = control.Uuid.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          control.Uuid.UUID, control.Uuid.UUID.Builder, control.Uuid.UUIDOrBuilder> identifierBuilder_;
      /**
       * <code>required .control.UUID identifier = 2;</code>
       *
       * <pre>
       *&#47; A unique identifier for this control
       * </pre>
       */
      public boolean hasIdentifier() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .control.UUID identifier = 2;</code>
       *
       * <pre>
       *&#47; A unique identifier for this control
       * </pre>
       */
      public control.Uuid.UUID getIdentifier() {
        if (identifierBuilder_ == null) {
          return identifier_;
        } else {
          return identifierBuilder_.getMessage();
        }
      }
      /**
       * <code>required .control.UUID identifier = 2;</code>
       *
       * <pre>
       *&#47; A unique identifier for this control
       * </pre>
       */
      public Builder setIdentifier(control.Uuid.UUID value) {
        if (identifierBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          identifier_ = value;
          onChanged();
        } else {
          identifierBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .control.UUID identifier = 2;</code>
       *
       * <pre>
       *&#47; A unique identifier for this control
       * </pre>
       */
      public Builder setIdentifier(
          control.Uuid.UUID.Builder builderForValue) {
        if (identifierBuilder_ == null) {
          identifier_ = builderForValue.build();
          onChanged();
        } else {
          identifierBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .control.UUID identifier = 2;</code>
       *
       * <pre>
       *&#47; A unique identifier for this control
       * </pre>
       */
      public Builder mergeIdentifier(control.Uuid.UUID value) {
        if (identifierBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              identifier_ != control.Uuid.UUID.getDefaultInstance()) {
            identifier_ =
              control.Uuid.UUID.newBuilder(identifier_).mergeFrom(value).buildPartial();
          } else {
            identifier_ = value;
          }
          onChanged();
        } else {
          identifierBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .control.UUID identifier = 2;</code>
       *
       * <pre>
       *&#47; A unique identifier for this control
       * </pre>
       */
      public Builder clearIdentifier() {
        if (identifierBuilder_ == null) {
          identifier_ = control.Uuid.UUID.getDefaultInstance();
          onChanged();
        } else {
          identifierBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .control.UUID identifier = 2;</code>
       *
       * <pre>
       *&#47; A unique identifier for this control
       * </pre>
       */
      public control.Uuid.UUID.Builder getIdentifierBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getIdentifierFieldBuilder().getBuilder();
      }
      /**
       * <code>required .control.UUID identifier = 2;</code>
       *
       * <pre>
       *&#47; A unique identifier for this control
       * </pre>
       */
      public control.Uuid.UUIDOrBuilder getIdentifierOrBuilder() {
        if (identifierBuilder_ != null) {
          return identifierBuilder_.getMessageOrBuilder();
        } else {
          return identifier_;
        }
      }
      /**
       * <code>required .control.UUID identifier = 2;</code>
       *
       * <pre>
       *&#47; A unique identifier for this control
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          control.Uuid.UUID, control.Uuid.UUID.Builder, control.Uuid.UUIDOrBuilder>
          getIdentifierFieldBuilder() {
        if (identifierBuilder_ == null) {
          identifierBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              control.Uuid.UUID, control.Uuid.UUID.Builder, control.Uuid.UUIDOrBuilder>(
                  getIdentifier(),
                  getParentForChildren(),
                  isClean());
          identifier_ = null;
        }
        return identifierBuilder_;
      }

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this ControlMessage.
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this ControlMessage.
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this ControlMessage.
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this ControlMessage.
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private control.Controlmessage.ControlMessage.ControlType controlType_ = control.Controlmessage.ControlMessage.ControlType.HeartbeatRequest;
      /**
       * <code>required .control.ControlMessage.ControlType controlType = 4;</code>
       *
       * <pre>
       *&#47; Type of wrapped control. Only the optional field corresponding to the value of ControlType should be set.
       * </pre>
       */
      public boolean hasControlType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .control.ControlMessage.ControlType controlType = 4;</code>
       *
       * <pre>
       *&#47; Type of wrapped control. Only the optional field corresponding to the value of ControlType should be set.
       * </pre>
       */
      public control.Controlmessage.ControlMessage.ControlType getControlType() {
        return controlType_;
      }
      /**
       * <code>required .control.ControlMessage.ControlType controlType = 4;</code>
       *
       * <pre>
       *&#47; Type of wrapped control. Only the optional field corresponding to the value of ControlType should be set.
       * </pre>
       */
      public Builder setControlType(control.Controlmessage.ControlMessage.ControlType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        controlType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .control.ControlMessage.ControlType controlType = 4;</code>
       *
       * <pre>
       *&#47; Type of wrapped control. Only the optional field corresponding to the value of ControlType should be set.
       * </pre>
       */
      public Builder clearControlType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        controlType_ = control.Controlmessage.ControlMessage.ControlType.HeartbeatRequest;
        onChanged();
        return this;
      }

      private control.Heartbeatrequest.HeartbeatRequest heartbeatRequest_ = control.Heartbeatrequest.HeartbeatRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          control.Heartbeatrequest.HeartbeatRequest, control.Heartbeatrequest.HeartbeatRequest.Builder, control.Heartbeatrequest.HeartbeatRequestOrBuilder> heartbeatRequestBuilder_;
      /**
       * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
       */
      public boolean hasHeartbeatRequest() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
       */
      public control.Heartbeatrequest.HeartbeatRequest getHeartbeatRequest() {
        if (heartbeatRequestBuilder_ == null) {
          return heartbeatRequest_;
        } else {
          return heartbeatRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
       */
      public Builder setHeartbeatRequest(control.Heartbeatrequest.HeartbeatRequest value) {
        if (heartbeatRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          heartbeatRequest_ = value;
          onChanged();
        } else {
          heartbeatRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
       */
      public Builder setHeartbeatRequest(
          control.Heartbeatrequest.HeartbeatRequest.Builder builderForValue) {
        if (heartbeatRequestBuilder_ == null) {
          heartbeatRequest_ = builderForValue.build();
          onChanged();
        } else {
          heartbeatRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
       */
      public Builder mergeHeartbeatRequest(control.Heartbeatrequest.HeartbeatRequest value) {
        if (heartbeatRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              heartbeatRequest_ != control.Heartbeatrequest.HeartbeatRequest.getDefaultInstance()) {
            heartbeatRequest_ =
              control.Heartbeatrequest.HeartbeatRequest.newBuilder(heartbeatRequest_).mergeFrom(value).buildPartial();
          } else {
            heartbeatRequest_ = value;
          }
          onChanged();
        } else {
          heartbeatRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
       */
      public Builder clearHeartbeatRequest() {
        if (heartbeatRequestBuilder_ == null) {
          heartbeatRequest_ = control.Heartbeatrequest.HeartbeatRequest.getDefaultInstance();
          onChanged();
        } else {
          heartbeatRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
       */
      public control.Heartbeatrequest.HeartbeatRequest.Builder getHeartbeatRequestBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getHeartbeatRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
       */
      public control.Heartbeatrequest.HeartbeatRequestOrBuilder getHeartbeatRequestOrBuilder() {
        if (heartbeatRequestBuilder_ != null) {
          return heartbeatRequestBuilder_.getMessageOrBuilder();
        } else {
          return heartbeatRequest_;
        }
      }
      /**
       * <code>optional .control.HeartbeatRequest heartbeatRequest = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          control.Heartbeatrequest.HeartbeatRequest, control.Heartbeatrequest.HeartbeatRequest.Builder, control.Heartbeatrequest.HeartbeatRequestOrBuilder>
          getHeartbeatRequestFieldBuilder() {
        if (heartbeatRequestBuilder_ == null) {
          heartbeatRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              control.Heartbeatrequest.HeartbeatRequest, control.Heartbeatrequest.HeartbeatRequest.Builder, control.Heartbeatrequest.HeartbeatRequestOrBuilder>(
                  getHeartbeatRequest(),
                  getParentForChildren(),
                  isClean());
          heartbeatRequest_ = null;
        }
        return heartbeatRequestBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:control.ControlMessage)
    }

    static {
      defaultInstance = new ControlMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:control.ControlMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_control_ControlMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_control_ControlMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024controlmessage.proto\022\007control\032\026heartbe" +
      "atrequest.proto\032\nuuid.proto\"\352\001\n\016ControlM" +
      "essage\022\016\n\006origin\030\001 \002(\t\022!\n\nidentifier\030\002 \002" +
      "(\0132\r.control.UUID\022\021\n\ttimestamp\030\003 \002(\003\0228\n\013" +
      "controlType\030\004 \002(\0162#.control.ControlMessa" +
      "ge.ControlType\0223\n\020heartbeatRequest\030\005 \001(\013" +
      "2\031.control.HeartbeatRequest\"#\n\013ControlTy" +
      "pe\022\024\n\020HeartbeatRequest\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          control.Heartbeatrequest.getDescriptor(),
          control.Uuid.getDescriptor(),
        }, assigner);
    internal_static_control_ControlMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_control_ControlMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_control_ControlMessage_descriptor,
        new String[] { "Origin", "Identifier", "Timestamp", "ControlType", "HeartbeatRequest", });
    control.Heartbeatrequest.getDescriptor();
    control.Uuid.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
