// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envelope.proto

package events;

public final class EnvelopeOuterClass {
  private EnvelopeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EnvelopeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:events.Envelope)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string origin = 1;</code>
     *
     * <pre>
     *&#47; Unique description of the origin of this event.
     * </pre>
     */
    boolean hasOrigin();
    /**
     * <code>required string origin = 1;</code>
     *
     * <pre>
     *&#47; Unique description of the origin of this event.
     * </pre>
     */
    String getOrigin();
    /**
     * <code>required string origin = 1;</code>
     *
     * <pre>
     *&#47; Unique description of the origin of this event.
     * </pre>
     */
    com.google.protobuf.ByteString
        getOriginBytes();

    /**
     * <code>required .events.Envelope.EventType eventType = 2;</code>
     *
     * <pre>
     *&#47; Type of wrapped event. Only the optional field corresponding to the value of eventType should be set.
     * </pre>
     */
    boolean hasEventType();
    /**
     * <code>required .events.Envelope.EventType eventType = 2;</code>
     *
     * <pre>
     *&#47; Type of wrapped event. Only the optional field corresponding to the value of eventType should be set.
     * </pre>
     */
    events.EnvelopeOuterClass.Envelope.EventType getEventType();

    /**
     * <code>optional int64 timestamp = 6;</code>
     *
     * <pre>
     *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this Envelope.
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 6;</code>
     *
     * <pre>
     *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this Envelope.
     * </pre>
     */
    long getTimestamp();

    /**
     * <code>optional .events.Heartbeat heartbeat = 3;</code>
     */
    boolean hasHeartbeat();
    /**
     * <code>optional .events.Heartbeat heartbeat = 3;</code>
     */
    events.HeartbeatOuterClass.Heartbeat getHeartbeat();
    /**
     * <code>optional .events.Heartbeat heartbeat = 3;</code>
     */
    events.HeartbeatOuterClass.HeartbeatOrBuilder getHeartbeatOrBuilder();

    /**
     * <code>optional .events.HttpStart httpStart = 4;</code>
     */
    boolean hasHttpStart();
    /**
     * <code>optional .events.HttpStart httpStart = 4;</code>
     */
    events.Http.HttpStart getHttpStart();
    /**
     * <code>optional .events.HttpStart httpStart = 4;</code>
     */
    events.Http.HttpStartOrBuilder getHttpStartOrBuilder();

    /**
     * <code>optional .events.HttpStop httpStop = 5;</code>
     */
    boolean hasHttpStop();
    /**
     * <code>optional .events.HttpStop httpStop = 5;</code>
     */
    events.Http.HttpStop getHttpStop();
    /**
     * <code>optional .events.HttpStop httpStop = 5;</code>
     */
    events.Http.HttpStopOrBuilder getHttpStopOrBuilder();

    /**
     * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
     */
    boolean hasHttpStartStop();
    /**
     * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
     */
    events.Http.HttpStartStop getHttpStartStop();
    /**
     * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
     */
    events.Http.HttpStartStopOrBuilder getHttpStartStopOrBuilder();

    /**
     * <code>optional .events.LogMessage logMessage = 8;</code>
     */
    boolean hasLogMessage();
    /**
     * <code>optional .events.LogMessage logMessage = 8;</code>
     */
    events.Log.LogMessage getLogMessage();
    /**
     * <code>optional .events.LogMessage logMessage = 8;</code>
     */
    events.Log.LogMessageOrBuilder getLogMessageOrBuilder();

    /**
     * <code>optional .events.ValueMetric valueMetric = 9;</code>
     */
    boolean hasValueMetric();
    /**
     * <code>optional .events.ValueMetric valueMetric = 9;</code>
     */
    events.Metric.ValueMetric getValueMetric();
    /**
     * <code>optional .events.ValueMetric valueMetric = 9;</code>
     */
    events.Metric.ValueMetricOrBuilder getValueMetricOrBuilder();

    /**
     * <code>optional .events.CounterEvent counterEvent = 10;</code>
     */
    boolean hasCounterEvent();
    /**
     * <code>optional .events.CounterEvent counterEvent = 10;</code>
     */
    events.Metric.CounterEvent getCounterEvent();
    /**
     * <code>optional .events.CounterEvent counterEvent = 10;</code>
     */
    events.Metric.CounterEventOrBuilder getCounterEventOrBuilder();

    /**
     * <code>optional .events.Error error = 11;</code>
     */
    boolean hasError();
    /**
     * <code>optional .events.Error error = 11;</code>
     */
    events.ErrorOuterClass.Error getError();
    /**
     * <code>optional .events.Error error = 11;</code>
     */
    events.ErrorOuterClass.ErrorOrBuilder getErrorOrBuilder();

    /**
     * <code>optional .events.ContainerMetric containerMetric = 12;</code>
     */
    boolean hasContainerMetric();
    /**
     * <code>optional .events.ContainerMetric containerMetric = 12;</code>
     */
    events.Metric.ContainerMetric getContainerMetric();
    /**
     * <code>optional .events.ContainerMetric containerMetric = 12;</code>
     */
    events.Metric.ContainerMetricOrBuilder getContainerMetricOrBuilder();
  }
  /**
   * Protobuf type {@code events.Envelope}
   *
   * <pre>
   *&#47; Envelope wraps an Event and adds metadata.
   * </pre>
   */
  public static final class Envelope extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:events.Envelope)
      EnvelopeOrBuilder {
    // Use Envelope.newBuilder() to construct.
    private Envelope(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Envelope(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Envelope defaultInstance;
    public static Envelope getDefaultInstance() {
      return defaultInstance;
    }

    public Envelope getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Envelope(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              origin_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              events.EnvelopeOuterClass.Envelope.EventType value = events.EnvelopeOuterClass.Envelope.EventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                eventType_ = value;
              }
              break;
            }
            case 26: {
              events.HeartbeatOuterClass.Heartbeat.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = heartbeat_.toBuilder();
              }
              heartbeat_ = input.readMessage(events.HeartbeatOuterClass.Heartbeat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(heartbeat_);
                heartbeat_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 34: {
              events.Http.HttpStart.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = httpStart_.toBuilder();
              }
              httpStart_ = input.readMessage(events.Http.HttpStart.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(httpStart_);
                httpStart_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 42: {
              events.Http.HttpStop.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = httpStop_.toBuilder();
              }
              httpStop_ = input.readMessage(events.Http.HttpStop.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(httpStop_);
                httpStop_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
            case 58: {
              events.Http.HttpStartStop.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = httpStartStop_.toBuilder();
              }
              httpStartStop_ = input.readMessage(events.Http.HttpStartStop.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(httpStartStop_);
                httpStartStop_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
            case 66: {
              events.Log.LogMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000080) == 0x00000080)) {
                subBuilder = logMessage_.toBuilder();
              }
              logMessage_ = input.readMessage(events.Log.LogMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(logMessage_);
                logMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000080;
              break;
            }
            case 74: {
              events.Metric.ValueMetric.Builder subBuilder = null;
              if (((bitField0_ & 0x00000100) == 0x00000100)) {
                subBuilder = valueMetric_.toBuilder();
              }
              valueMetric_ = input.readMessage(events.Metric.ValueMetric.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(valueMetric_);
                valueMetric_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000100;
              break;
            }
            case 82: {
              events.Metric.CounterEvent.Builder subBuilder = null;
              if (((bitField0_ & 0x00000200) == 0x00000200)) {
                subBuilder = counterEvent_.toBuilder();
              }
              counterEvent_ = input.readMessage(events.Metric.CounterEvent.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(counterEvent_);
                counterEvent_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000200;
              break;
            }
            case 90: {
              events.ErrorOuterClass.Error.Builder subBuilder = null;
              if (((bitField0_ & 0x00000400) == 0x00000400)) {
                subBuilder = error_.toBuilder();
              }
              error_ = input.readMessage(events.ErrorOuterClass.Error.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(error_);
                error_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000400;
              break;
            }
            case 98: {
              events.Metric.ContainerMetric.Builder subBuilder = null;
              if (((bitField0_ & 0x00000800) == 0x00000800)) {
                subBuilder = containerMetric_.toBuilder();
              }
              containerMetric_ = input.readMessage(events.Metric.ContainerMetric.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(containerMetric_);
                containerMetric_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000800;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return events.EnvelopeOuterClass.internal_static_events_Envelope_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return events.EnvelopeOuterClass.internal_static_events_Envelope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              events.EnvelopeOuterClass.Envelope.class, events.EnvelopeOuterClass.Envelope.Builder.class);
    }

    public static com.google.protobuf.Parser<Envelope> PARSER =
        new com.google.protobuf.AbstractParser<Envelope>() {
      public Envelope parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Envelope(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Envelope> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code events.Envelope.EventType}
     *
     * <pre>
     *&#47; Type of the wrapped event.
     * </pre>
     */
    public enum EventType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Heartbeat = 1;</code>
       */
      Heartbeat(0, 1),
      /**
       * <code>HttpStart = 2;</code>
       */
      HttpStart(1, 2),
      /**
       * <code>HttpStop = 3;</code>
       */
      HttpStop(2, 3),
      /**
       * <code>HttpStartStop = 4;</code>
       */
      HttpStartStop(3, 4),
      /**
       * <code>LogMessage = 5;</code>
       */
      LogMessage(4, 5),
      /**
       * <code>ValueMetric = 6;</code>
       */
      ValueMetric(5, 6),
      /**
       * <code>CounterEvent = 7;</code>
       */
      CounterEvent(6, 7),
      /**
       * <code>Error = 8;</code>
       */
      Error(7, 8),
      /**
       * <code>ContainerMetric = 9;</code>
       */
      ContainerMetric(8, 9),
      ;

      /**
       * <code>Heartbeat = 1;</code>
       */
      public static final int Heartbeat_VALUE = 1;
      /**
       * <code>HttpStart = 2;</code>
       */
      public static final int HttpStart_VALUE = 2;
      /**
       * <code>HttpStop = 3;</code>
       */
      public static final int HttpStop_VALUE = 3;
      /**
       * <code>HttpStartStop = 4;</code>
       */
      public static final int HttpStartStop_VALUE = 4;
      /**
       * <code>LogMessage = 5;</code>
       */
      public static final int LogMessage_VALUE = 5;
      /**
       * <code>ValueMetric = 6;</code>
       */
      public static final int ValueMetric_VALUE = 6;
      /**
       * <code>CounterEvent = 7;</code>
       */
      public static final int CounterEvent_VALUE = 7;
      /**
       * <code>Error = 8;</code>
       */
      public static final int Error_VALUE = 8;
      /**
       * <code>ContainerMetric = 9;</code>
       */
      public static final int ContainerMetric_VALUE = 9;


      public final int getNumber() { return value; }

      public static EventType valueOf(int value) {
        switch (value) {
          case 1: return Heartbeat;
          case 2: return HttpStart;
          case 3: return HttpStop;
          case 4: return HttpStartStop;
          case 5: return LogMessage;
          case 6: return ValueMetric;
          case 7: return CounterEvent;
          case 8: return Error;
          case 9: return ContainerMetric;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              public EventType findValueByNumber(int number) {
                return EventType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return events.EnvelopeOuterClass.Envelope.getDescriptor().getEnumTypes().get(0);
      }

      private static final EventType[] VALUES = values();

      public static EventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private EventType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:events.Envelope.EventType)
    }

    private int bitField0_;
    public static final int ORIGIN_FIELD_NUMBER = 1;
    private Object origin_;
    /**
     * <code>required string origin = 1;</code>
     *
     * <pre>
     *&#47; Unique description of the origin of this event.
     * </pre>
     */
    public boolean hasOrigin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string origin = 1;</code>
     *
     * <pre>
     *&#47; Unique description of the origin of this event.
     * </pre>
     */
    public String getOrigin() {
      Object ref = origin_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          origin_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string origin = 1;</code>
     *
     * <pre>
     *&#47; Unique description of the origin of this event.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOriginBytes() {
      Object ref = origin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        origin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTTYPE_FIELD_NUMBER = 2;
    private events.EnvelopeOuterClass.Envelope.EventType eventType_;
    /**
     * <code>required .events.Envelope.EventType eventType = 2;</code>
     *
     * <pre>
     *&#47; Type of wrapped event. Only the optional field corresponding to the value of eventType should be set.
     * </pre>
     */
    public boolean hasEventType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .events.Envelope.EventType eventType = 2;</code>
     *
     * <pre>
     *&#47; Type of wrapped event. Only the optional field corresponding to the value of eventType should be set.
     * </pre>
     */
    public events.EnvelopeOuterClass.Envelope.EventType getEventType() {
      return eventType_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 6;</code>
     *
     * <pre>
     *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this Envelope.
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 timestamp = 6;</code>
     *
     * <pre>
     *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this Envelope.
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int HEARTBEAT_FIELD_NUMBER = 3;
    private events.HeartbeatOuterClass.Heartbeat heartbeat_;
    /**
     * <code>optional .events.Heartbeat heartbeat = 3;</code>
     */
    public boolean hasHeartbeat() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .events.Heartbeat heartbeat = 3;</code>
     */
    public events.HeartbeatOuterClass.Heartbeat getHeartbeat() {
      return heartbeat_;
    }
    /**
     * <code>optional .events.Heartbeat heartbeat = 3;</code>
     */
    public events.HeartbeatOuterClass.HeartbeatOrBuilder getHeartbeatOrBuilder() {
      return heartbeat_;
    }

    public static final int HTTPSTART_FIELD_NUMBER = 4;
    private events.Http.HttpStart httpStart_;
    /**
     * <code>optional .events.HttpStart httpStart = 4;</code>
     */
    public boolean hasHttpStart() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .events.HttpStart httpStart = 4;</code>
     */
    public events.Http.HttpStart getHttpStart() {
      return httpStart_;
    }
    /**
     * <code>optional .events.HttpStart httpStart = 4;</code>
     */
    public events.Http.HttpStartOrBuilder getHttpStartOrBuilder() {
      return httpStart_;
    }

    public static final int HTTPSTOP_FIELD_NUMBER = 5;
    private events.Http.HttpStop httpStop_;
    /**
     * <code>optional .events.HttpStop httpStop = 5;</code>
     */
    public boolean hasHttpStop() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .events.HttpStop httpStop = 5;</code>
     */
    public events.Http.HttpStop getHttpStop() {
      return httpStop_;
    }
    /**
     * <code>optional .events.HttpStop httpStop = 5;</code>
     */
    public events.Http.HttpStopOrBuilder getHttpStopOrBuilder() {
      return httpStop_;
    }

    public static final int HTTPSTARTSTOP_FIELD_NUMBER = 7;
    private events.Http.HttpStartStop httpStartStop_;
    /**
     * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
     */
    public boolean hasHttpStartStop() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
     */
    public events.Http.HttpStartStop getHttpStartStop() {
      return httpStartStop_;
    }
    /**
     * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
     */
    public events.Http.HttpStartStopOrBuilder getHttpStartStopOrBuilder() {
      return httpStartStop_;
    }

    public static final int LOGMESSAGE_FIELD_NUMBER = 8;
    private events.Log.LogMessage logMessage_;
    /**
     * <code>optional .events.LogMessage logMessage = 8;</code>
     */
    public boolean hasLogMessage() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .events.LogMessage logMessage = 8;</code>
     */
    public events.Log.LogMessage getLogMessage() {
      return logMessage_;
    }
    /**
     * <code>optional .events.LogMessage logMessage = 8;</code>
     */
    public events.Log.LogMessageOrBuilder getLogMessageOrBuilder() {
      return logMessage_;
    }

    public static final int VALUEMETRIC_FIELD_NUMBER = 9;
    private events.Metric.ValueMetric valueMetric_;
    /**
     * <code>optional .events.ValueMetric valueMetric = 9;</code>
     */
    public boolean hasValueMetric() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional .events.ValueMetric valueMetric = 9;</code>
     */
    public events.Metric.ValueMetric getValueMetric() {
      return valueMetric_;
    }
    /**
     * <code>optional .events.ValueMetric valueMetric = 9;</code>
     */
    public events.Metric.ValueMetricOrBuilder getValueMetricOrBuilder() {
      return valueMetric_;
    }

    public static final int COUNTEREVENT_FIELD_NUMBER = 10;
    private events.Metric.CounterEvent counterEvent_;
    /**
     * <code>optional .events.CounterEvent counterEvent = 10;</code>
     */
    public boolean hasCounterEvent() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional .events.CounterEvent counterEvent = 10;</code>
     */
    public events.Metric.CounterEvent getCounterEvent() {
      return counterEvent_;
    }
    /**
     * <code>optional .events.CounterEvent counterEvent = 10;</code>
     */
    public events.Metric.CounterEventOrBuilder getCounterEventOrBuilder() {
      return counterEvent_;
    }

    public static final int ERROR_FIELD_NUMBER = 11;
    private events.ErrorOuterClass.Error error_;
    /**
     * <code>optional .events.Error error = 11;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional .events.Error error = 11;</code>
     */
    public events.ErrorOuterClass.Error getError() {
      return error_;
    }
    /**
     * <code>optional .events.Error error = 11;</code>
     */
    public events.ErrorOuterClass.ErrorOrBuilder getErrorOrBuilder() {
      return error_;
    }

    public static final int CONTAINERMETRIC_FIELD_NUMBER = 12;
    private events.Metric.ContainerMetric containerMetric_;
    /**
     * <code>optional .events.ContainerMetric containerMetric = 12;</code>
     */
    public boolean hasContainerMetric() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional .events.ContainerMetric containerMetric = 12;</code>
     */
    public events.Metric.ContainerMetric getContainerMetric() {
      return containerMetric_;
    }
    /**
     * <code>optional .events.ContainerMetric containerMetric = 12;</code>
     */
    public events.Metric.ContainerMetricOrBuilder getContainerMetricOrBuilder() {
      return containerMetric_;
    }

    private void initFields() {
      origin_ = "";
      eventType_ = events.EnvelopeOuterClass.Envelope.EventType.Heartbeat;
      timestamp_ = 0L;
      heartbeat_ = events.HeartbeatOuterClass.Heartbeat.getDefaultInstance();
      httpStart_ = events.Http.HttpStart.getDefaultInstance();
      httpStop_ = events.Http.HttpStop.getDefaultInstance();
      httpStartStop_ = events.Http.HttpStartStop.getDefaultInstance();
      logMessage_ = events.Log.LogMessage.getDefaultInstance();
      valueMetric_ = events.Metric.ValueMetric.getDefaultInstance();
      counterEvent_ = events.Metric.CounterEvent.getDefaultInstance();
      error_ = events.ErrorOuterClass.Error.getDefaultInstance();
      containerMetric_ = events.Metric.ContainerMetric.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOrigin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEventType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasHeartbeat()) {
        if (!getHeartbeat().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasHttpStart()) {
        if (!getHttpStart().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasHttpStop()) {
        if (!getHttpStop().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasHttpStartStop()) {
        if (!getHttpStartStop().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasLogMessage()) {
        if (!getLogMessage().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasValueMetric()) {
        if (!getValueMetric().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasCounterEvent()) {
        if (!getCounterEvent().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasError()) {
        if (!getError().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasContainerMetric()) {
        if (!getContainerMetric().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOriginBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, eventType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(3, heartbeat_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(4, httpStart_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(5, httpStop_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(6, timestamp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, httpStartStop_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, logMessage_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeMessage(9, valueMetric_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeMessage(10, counterEvent_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeMessage(11, error_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeMessage(12, containerMetric_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOriginBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, eventType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, heartbeat_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, httpStart_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, httpStop_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, timestamp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, httpStartStop_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, logMessage_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, valueMetric_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, counterEvent_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, error_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, containerMetric_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static events.EnvelopeOuterClass.Envelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static events.EnvelopeOuterClass.Envelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static events.EnvelopeOuterClass.Envelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static events.EnvelopeOuterClass.Envelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static events.EnvelopeOuterClass.Envelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static events.EnvelopeOuterClass.Envelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static events.EnvelopeOuterClass.Envelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static events.EnvelopeOuterClass.Envelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static events.EnvelopeOuterClass.Envelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static events.EnvelopeOuterClass.Envelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(events.EnvelopeOuterClass.Envelope prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code events.Envelope}
     *
     * <pre>
     *&#47; Envelope wraps an Event and adds metadata.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:events.Envelope)
        events.EnvelopeOuterClass.EnvelopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return events.EnvelopeOuterClass.internal_static_events_Envelope_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return events.EnvelopeOuterClass.internal_static_events_Envelope_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                events.EnvelopeOuterClass.Envelope.class, events.EnvelopeOuterClass.Envelope.Builder.class);
      }

      // Construct using events.EnvelopeOuterClass.Envelope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeartbeatFieldBuilder();
          getHttpStartFieldBuilder();
          getHttpStopFieldBuilder();
          getHttpStartStopFieldBuilder();
          getLogMessageFieldBuilder();
          getValueMetricFieldBuilder();
          getCounterEventFieldBuilder();
          getErrorFieldBuilder();
          getContainerMetricFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        origin_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        eventType_ = events.EnvelopeOuterClass.Envelope.EventType.Heartbeat;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (heartbeatBuilder_ == null) {
          heartbeat_ = events.HeartbeatOuterClass.Heartbeat.getDefaultInstance();
        } else {
          heartbeatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (httpStartBuilder_ == null) {
          httpStart_ = events.Http.HttpStart.getDefaultInstance();
        } else {
          httpStartBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (httpStopBuilder_ == null) {
          httpStop_ = events.Http.HttpStop.getDefaultInstance();
        } else {
          httpStopBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (httpStartStopBuilder_ == null) {
          httpStartStop_ = events.Http.HttpStartStop.getDefaultInstance();
        } else {
          httpStartStopBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        if (logMessageBuilder_ == null) {
          logMessage_ = events.Log.LogMessage.getDefaultInstance();
        } else {
          logMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        if (valueMetricBuilder_ == null) {
          valueMetric_ = events.Metric.ValueMetric.getDefaultInstance();
        } else {
          valueMetricBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        if (counterEventBuilder_ == null) {
          counterEvent_ = events.Metric.CounterEvent.getDefaultInstance();
        } else {
          counterEventBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        if (errorBuilder_ == null) {
          error_ = events.ErrorOuterClass.Error.getDefaultInstance();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        if (containerMetricBuilder_ == null) {
          containerMetric_ = events.Metric.ContainerMetric.getDefaultInstance();
        } else {
          containerMetricBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return events.EnvelopeOuterClass.internal_static_events_Envelope_descriptor;
      }

      public events.EnvelopeOuterClass.Envelope getDefaultInstanceForType() {
        return events.EnvelopeOuterClass.Envelope.getDefaultInstance();
      }

      public events.EnvelopeOuterClass.Envelope build() {
        events.EnvelopeOuterClass.Envelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public events.EnvelopeOuterClass.Envelope buildPartial() {
        events.EnvelopeOuterClass.Envelope result = new events.EnvelopeOuterClass.Envelope(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.origin_ = origin_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.eventType_ = eventType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (heartbeatBuilder_ == null) {
          result.heartbeat_ = heartbeat_;
        } else {
          result.heartbeat_ = heartbeatBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (httpStartBuilder_ == null) {
          result.httpStart_ = httpStart_;
        } else {
          result.httpStart_ = httpStartBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (httpStopBuilder_ == null) {
          result.httpStop_ = httpStop_;
        } else {
          result.httpStop_ = httpStopBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (httpStartStopBuilder_ == null) {
          result.httpStartStop_ = httpStartStop_;
        } else {
          result.httpStartStop_ = httpStartStopBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (logMessageBuilder_ == null) {
          result.logMessage_ = logMessage_;
        } else {
          result.logMessage_ = logMessageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        if (valueMetricBuilder_ == null) {
          result.valueMetric_ = valueMetric_;
        } else {
          result.valueMetric_ = valueMetricBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        if (counterEventBuilder_ == null) {
          result.counterEvent_ = counterEvent_;
        } else {
          result.counterEvent_ = counterEventBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        if (containerMetricBuilder_ == null) {
          result.containerMetric_ = containerMetric_;
        } else {
          result.containerMetric_ = containerMetricBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof events.EnvelopeOuterClass.Envelope) {
          return mergeFrom((events.EnvelopeOuterClass.Envelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(events.EnvelopeOuterClass.Envelope other) {
        if (other == events.EnvelopeOuterClass.Envelope.getDefaultInstance()) return this;
        if (other.hasOrigin()) {
          bitField0_ |= 0x00000001;
          origin_ = other.origin_;
          onChanged();
        }
        if (other.hasEventType()) {
          setEventType(other.getEventType());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasHeartbeat()) {
          mergeHeartbeat(other.getHeartbeat());
        }
        if (other.hasHttpStart()) {
          mergeHttpStart(other.getHttpStart());
        }
        if (other.hasHttpStop()) {
          mergeHttpStop(other.getHttpStop());
        }
        if (other.hasHttpStartStop()) {
          mergeHttpStartStop(other.getHttpStartStop());
        }
        if (other.hasLogMessage()) {
          mergeLogMessage(other.getLogMessage());
        }
        if (other.hasValueMetric()) {
          mergeValueMetric(other.getValueMetric());
        }
        if (other.hasCounterEvent()) {
          mergeCounterEvent(other.getCounterEvent());
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        if (other.hasContainerMetric()) {
          mergeContainerMetric(other.getContainerMetric());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOrigin()) {

          return false;
        }
        if (!hasEventType()) {

          return false;
        }
        if (hasHeartbeat()) {
          if (!getHeartbeat().isInitialized()) {

            return false;
          }
        }
        if (hasHttpStart()) {
          if (!getHttpStart().isInitialized()) {

            return false;
          }
        }
        if (hasHttpStop()) {
          if (!getHttpStop().isInitialized()) {

            return false;
          }
        }
        if (hasHttpStartStop()) {
          if (!getHttpStartStop().isInitialized()) {

            return false;
          }
        }
        if (hasLogMessage()) {
          if (!getLogMessage().isInitialized()) {

            return false;
          }
        }
        if (hasValueMetric()) {
          if (!getValueMetric().isInitialized()) {

            return false;
          }
        }
        if (hasCounterEvent()) {
          if (!getCounterEvent().isInitialized()) {

            return false;
          }
        }
        if (hasError()) {
          if (!getError().isInitialized()) {

            return false;
          }
        }
        if (hasContainerMetric()) {
          if (!getContainerMetric().isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        events.EnvelopeOuterClass.Envelope parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (events.EnvelopeOuterClass.Envelope) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object origin_ = "";
      /**
       * <code>required string origin = 1;</code>
       *
       * <pre>
       *&#47; Unique description of the origin of this event.
       * </pre>
       */
      public boolean hasOrigin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string origin = 1;</code>
       *
       * <pre>
       *&#47; Unique description of the origin of this event.
       * </pre>
       */
      public String getOrigin() {
        Object ref = origin_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            origin_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string origin = 1;</code>
       *
       * <pre>
       *&#47; Unique description of the origin of this event.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOriginBytes() {
        Object ref = origin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          origin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string origin = 1;</code>
       *
       * <pre>
       *&#47; Unique description of the origin of this event.
       * </pre>
       */
      public Builder setOrigin(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        origin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string origin = 1;</code>
       *
       * <pre>
       *&#47; Unique description of the origin of this event.
       * </pre>
       */
      public Builder clearOrigin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        origin_ = getDefaultInstance().getOrigin();
        onChanged();
        return this;
      }
      /**
       * <code>required string origin = 1;</code>
       *
       * <pre>
       *&#47; Unique description of the origin of this event.
       * </pre>
       */
      public Builder setOriginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        origin_ = value;
        onChanged();
        return this;
      }

      private events.EnvelopeOuterClass.Envelope.EventType eventType_ = events.EnvelopeOuterClass.Envelope.EventType.Heartbeat;
      /**
       * <code>required .events.Envelope.EventType eventType = 2;</code>
       *
       * <pre>
       *&#47; Type of wrapped event. Only the optional field corresponding to the value of eventType should be set.
       * </pre>
       */
      public boolean hasEventType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .events.Envelope.EventType eventType = 2;</code>
       *
       * <pre>
       *&#47; Type of wrapped event. Only the optional field corresponding to the value of eventType should be set.
       * </pre>
       */
      public events.EnvelopeOuterClass.Envelope.EventType getEventType() {
        return eventType_;
      }
      /**
       * <code>required .events.Envelope.EventType eventType = 2;</code>
       *
       * <pre>
       *&#47; Type of wrapped event. Only the optional field corresponding to the value of eventType should be set.
       * </pre>
       */
      public Builder setEventType(events.EnvelopeOuterClass.Envelope.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .events.Envelope.EventType eventType = 2;</code>
       *
       * <pre>
       *&#47; Type of wrapped event. Only the optional field corresponding to the value of eventType should be set.
       * </pre>
       */
      public Builder clearEventType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        eventType_ = events.EnvelopeOuterClass.Envelope.EventType.Heartbeat;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 6;</code>
       *
       * <pre>
       *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this Envelope.
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 timestamp = 6;</code>
       *
       * <pre>
       *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this Envelope.
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 6;</code>
       *
       * <pre>
       *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this Envelope.
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 6;</code>
       *
       * <pre>
       *&#47; UNIX timestamp (in nanoseconds) event was wrapped in this Envelope.
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private events.HeartbeatOuterClass.Heartbeat heartbeat_ = events.HeartbeatOuterClass.Heartbeat.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          HeartbeatOuterClass.Heartbeat, HeartbeatOuterClass.Heartbeat.Builder, HeartbeatOuterClass.HeartbeatOrBuilder> heartbeatBuilder_;
      /**
       * <code>optional .events.Heartbeat heartbeat = 3;</code>
       */
      public boolean hasHeartbeat() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .events.Heartbeat heartbeat = 3;</code>
       */
      public events.HeartbeatOuterClass.Heartbeat getHeartbeat() {
        if (heartbeatBuilder_ == null) {
          return heartbeat_;
        } else {
          return heartbeatBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .events.Heartbeat heartbeat = 3;</code>
       */
      public Builder setHeartbeat(events.HeartbeatOuterClass.Heartbeat value) {
        if (heartbeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          heartbeat_ = value;
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .events.Heartbeat heartbeat = 3;</code>
       */
      public Builder setHeartbeat(
          events.HeartbeatOuterClass.Heartbeat.Builder builderForValue) {
        if (heartbeatBuilder_ == null) {
          heartbeat_ = builderForValue.build();
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .events.Heartbeat heartbeat = 3;</code>
       */
      public Builder mergeHeartbeat(events.HeartbeatOuterClass.Heartbeat value) {
        if (heartbeatBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              heartbeat_ != events.HeartbeatOuterClass.Heartbeat.getDefaultInstance()) {
            heartbeat_ =
              events.HeartbeatOuterClass.Heartbeat.newBuilder(heartbeat_).mergeFrom(value).buildPartial();
          } else {
            heartbeat_ = value;
          }
          onChanged();
        } else {
          heartbeatBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .events.Heartbeat heartbeat = 3;</code>
       */
      public Builder clearHeartbeat() {
        if (heartbeatBuilder_ == null) {
          heartbeat_ = events.HeartbeatOuterClass.Heartbeat.getDefaultInstance();
          onChanged();
        } else {
          heartbeatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .events.Heartbeat heartbeat = 3;</code>
       */
      public events.HeartbeatOuterClass.Heartbeat.Builder getHeartbeatBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getHeartbeatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .events.Heartbeat heartbeat = 3;</code>
       */
      public events.HeartbeatOuterClass.HeartbeatOrBuilder getHeartbeatOrBuilder() {
        if (heartbeatBuilder_ != null) {
          return heartbeatBuilder_.getMessageOrBuilder();
        } else {
          return heartbeat_;
        }
      }
      /**
       * <code>optional .events.Heartbeat heartbeat = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          HeartbeatOuterClass.Heartbeat, HeartbeatOuterClass.Heartbeat.Builder, HeartbeatOuterClass.HeartbeatOrBuilder>
          getHeartbeatFieldBuilder() {
        if (heartbeatBuilder_ == null) {
          heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              HeartbeatOuterClass.Heartbeat, HeartbeatOuterClass.Heartbeat.Builder, HeartbeatOuterClass.HeartbeatOrBuilder>(
                  getHeartbeat(),
                  getParentForChildren(),
                  isClean());
          heartbeat_ = null;
        }
        return heartbeatBuilder_;
      }

      private events.Http.HttpStart httpStart_ = events.Http.HttpStart.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          events.Http.HttpStart, events.Http.HttpStart.Builder, events.Http.HttpStartOrBuilder> httpStartBuilder_;
      /**
       * <code>optional .events.HttpStart httpStart = 4;</code>
       */
      public boolean hasHttpStart() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .events.HttpStart httpStart = 4;</code>
       */
      public events.Http.HttpStart getHttpStart() {
        if (httpStartBuilder_ == null) {
          return httpStart_;
        } else {
          return httpStartBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .events.HttpStart httpStart = 4;</code>
       */
      public Builder setHttpStart(events.Http.HttpStart value) {
        if (httpStartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          httpStart_ = value;
          onChanged();
        } else {
          httpStartBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .events.HttpStart httpStart = 4;</code>
       */
      public Builder setHttpStart(
          events.Http.HttpStart.Builder builderForValue) {
        if (httpStartBuilder_ == null) {
          httpStart_ = builderForValue.build();
          onChanged();
        } else {
          httpStartBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .events.HttpStart httpStart = 4;</code>
       */
      public Builder mergeHttpStart(events.Http.HttpStart value) {
        if (httpStartBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              httpStart_ != events.Http.HttpStart.getDefaultInstance()) {
            httpStart_ =
              events.Http.HttpStart.newBuilder(httpStart_).mergeFrom(value).buildPartial();
          } else {
            httpStart_ = value;
          }
          onChanged();
        } else {
          httpStartBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .events.HttpStart httpStart = 4;</code>
       */
      public Builder clearHttpStart() {
        if (httpStartBuilder_ == null) {
          httpStart_ = events.Http.HttpStart.getDefaultInstance();
          onChanged();
        } else {
          httpStartBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .events.HttpStart httpStart = 4;</code>
       */
      public events.Http.HttpStart.Builder getHttpStartBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getHttpStartFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .events.HttpStart httpStart = 4;</code>
       */
      public events.Http.HttpStartOrBuilder getHttpStartOrBuilder() {
        if (httpStartBuilder_ != null) {
          return httpStartBuilder_.getMessageOrBuilder();
        } else {
          return httpStart_;
        }
      }
      /**
       * <code>optional .events.HttpStart httpStart = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          events.Http.HttpStart, events.Http.HttpStart.Builder, events.Http.HttpStartOrBuilder>
          getHttpStartFieldBuilder() {
        if (httpStartBuilder_ == null) {
          httpStartBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              events.Http.HttpStart, events.Http.HttpStart.Builder, events.Http.HttpStartOrBuilder>(
                  getHttpStart(),
                  getParentForChildren(),
                  isClean());
          httpStart_ = null;
        }
        return httpStartBuilder_;
      }

      private events.Http.HttpStop httpStop_ = events.Http.HttpStop.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          events.Http.HttpStop, events.Http.HttpStop.Builder, events.Http.HttpStopOrBuilder> httpStopBuilder_;
      /**
       * <code>optional .events.HttpStop httpStop = 5;</code>
       */
      public boolean hasHttpStop() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .events.HttpStop httpStop = 5;</code>
       */
      public events.Http.HttpStop getHttpStop() {
        if (httpStopBuilder_ == null) {
          return httpStop_;
        } else {
          return httpStopBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .events.HttpStop httpStop = 5;</code>
       */
      public Builder setHttpStop(events.Http.HttpStop value) {
        if (httpStopBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          httpStop_ = value;
          onChanged();
        } else {
          httpStopBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .events.HttpStop httpStop = 5;</code>
       */
      public Builder setHttpStop(
          events.Http.HttpStop.Builder builderForValue) {
        if (httpStopBuilder_ == null) {
          httpStop_ = builderForValue.build();
          onChanged();
        } else {
          httpStopBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .events.HttpStop httpStop = 5;</code>
       */
      public Builder mergeHttpStop(events.Http.HttpStop value) {
        if (httpStopBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              httpStop_ != events.Http.HttpStop.getDefaultInstance()) {
            httpStop_ =
              events.Http.HttpStop.newBuilder(httpStop_).mergeFrom(value).buildPartial();
          } else {
            httpStop_ = value;
          }
          onChanged();
        } else {
          httpStopBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .events.HttpStop httpStop = 5;</code>
       */
      public Builder clearHttpStop() {
        if (httpStopBuilder_ == null) {
          httpStop_ = events.Http.HttpStop.getDefaultInstance();
          onChanged();
        } else {
          httpStopBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .events.HttpStop httpStop = 5;</code>
       */
      public events.Http.HttpStop.Builder getHttpStopBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getHttpStopFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .events.HttpStop httpStop = 5;</code>
       */
      public events.Http.HttpStopOrBuilder getHttpStopOrBuilder() {
        if (httpStopBuilder_ != null) {
          return httpStopBuilder_.getMessageOrBuilder();
        } else {
          return httpStop_;
        }
      }
      /**
       * <code>optional .events.HttpStop httpStop = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          events.Http.HttpStop, events.Http.HttpStop.Builder, events.Http.HttpStopOrBuilder>
          getHttpStopFieldBuilder() {
        if (httpStopBuilder_ == null) {
          httpStopBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              events.Http.HttpStop, events.Http.HttpStop.Builder, events.Http.HttpStopOrBuilder>(
                  getHttpStop(),
                  getParentForChildren(),
                  isClean());
          httpStop_ = null;
        }
        return httpStopBuilder_;
      }

      private events.Http.HttpStartStop httpStartStop_ = events.Http.HttpStartStop.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          events.Http.HttpStartStop, events.Http.HttpStartStop.Builder, events.Http.HttpStartStopOrBuilder> httpStartStopBuilder_;
      /**
       * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
       */
      public boolean hasHttpStartStop() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
       */
      public events.Http.HttpStartStop getHttpStartStop() {
        if (httpStartStopBuilder_ == null) {
          return httpStartStop_;
        } else {
          return httpStartStopBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
       */
      public Builder setHttpStartStop(events.Http.HttpStartStop value) {
        if (httpStartStopBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          httpStartStop_ = value;
          onChanged();
        } else {
          httpStartStopBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
       */
      public Builder setHttpStartStop(
          events.Http.HttpStartStop.Builder builderForValue) {
        if (httpStartStopBuilder_ == null) {
          httpStartStop_ = builderForValue.build();
          onChanged();
        } else {
          httpStartStopBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
       */
      public Builder mergeHttpStartStop(events.Http.HttpStartStop value) {
        if (httpStartStopBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              httpStartStop_ != events.Http.HttpStartStop.getDefaultInstance()) {
            httpStartStop_ =
              events.Http.HttpStartStop.newBuilder(httpStartStop_).mergeFrom(value).buildPartial();
          } else {
            httpStartStop_ = value;
          }
          onChanged();
        } else {
          httpStartStopBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
       */
      public Builder clearHttpStartStop() {
        if (httpStartStopBuilder_ == null) {
          httpStartStop_ = events.Http.HttpStartStop.getDefaultInstance();
          onChanged();
        } else {
          httpStartStopBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
       */
      public events.Http.HttpStartStop.Builder getHttpStartStopBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getHttpStartStopFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
       */
      public events.Http.HttpStartStopOrBuilder getHttpStartStopOrBuilder() {
        if (httpStartStopBuilder_ != null) {
          return httpStartStopBuilder_.getMessageOrBuilder();
        } else {
          return httpStartStop_;
        }
      }
      /**
       * <code>optional .events.HttpStartStop httpStartStop = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          events.Http.HttpStartStop, events.Http.HttpStartStop.Builder, events.Http.HttpStartStopOrBuilder>
          getHttpStartStopFieldBuilder() {
        if (httpStartStopBuilder_ == null) {
          httpStartStopBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              events.Http.HttpStartStop, events.Http.HttpStartStop.Builder, events.Http.HttpStartStopOrBuilder>(
                  getHttpStartStop(),
                  getParentForChildren(),
                  isClean());
          httpStartStop_ = null;
        }
        return httpStartStopBuilder_;
      }

      private events.Log.LogMessage logMessage_ = events.Log.LogMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          events.Log.LogMessage, events.Log.LogMessage.Builder, events.Log.LogMessageOrBuilder> logMessageBuilder_;
      /**
       * <code>optional .events.LogMessage logMessage = 8;</code>
       */
      public boolean hasLogMessage() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .events.LogMessage logMessage = 8;</code>
       */
      public events.Log.LogMessage getLogMessage() {
        if (logMessageBuilder_ == null) {
          return logMessage_;
        } else {
          return logMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .events.LogMessage logMessage = 8;</code>
       */
      public Builder setLogMessage(events.Log.LogMessage value) {
        if (logMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          logMessage_ = value;
          onChanged();
        } else {
          logMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .events.LogMessage logMessage = 8;</code>
       */
      public Builder setLogMessage(
          events.Log.LogMessage.Builder builderForValue) {
        if (logMessageBuilder_ == null) {
          logMessage_ = builderForValue.build();
          onChanged();
        } else {
          logMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .events.LogMessage logMessage = 8;</code>
       */
      public Builder mergeLogMessage(events.Log.LogMessage value) {
        if (logMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              logMessage_ != events.Log.LogMessage.getDefaultInstance()) {
            logMessage_ =
              events.Log.LogMessage.newBuilder(logMessage_).mergeFrom(value).buildPartial();
          } else {
            logMessage_ = value;
          }
          onChanged();
        } else {
          logMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .events.LogMessage logMessage = 8;</code>
       */
      public Builder clearLogMessage() {
        if (logMessageBuilder_ == null) {
          logMessage_ = events.Log.LogMessage.getDefaultInstance();
          onChanged();
        } else {
          logMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>optional .events.LogMessage logMessage = 8;</code>
       */
      public events.Log.LogMessage.Builder getLogMessageBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getLogMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .events.LogMessage logMessage = 8;</code>
       */
      public events.Log.LogMessageOrBuilder getLogMessageOrBuilder() {
        if (logMessageBuilder_ != null) {
          return logMessageBuilder_.getMessageOrBuilder();
        } else {
          return logMessage_;
        }
      }
      /**
       * <code>optional .events.LogMessage logMessage = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          events.Log.LogMessage, events.Log.LogMessage.Builder, events.Log.LogMessageOrBuilder>
          getLogMessageFieldBuilder() {
        if (logMessageBuilder_ == null) {
          logMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              events.Log.LogMessage, events.Log.LogMessage.Builder, events.Log.LogMessageOrBuilder>(
                  getLogMessage(),
                  getParentForChildren(),
                  isClean());
          logMessage_ = null;
        }
        return logMessageBuilder_;
      }

      private events.Metric.ValueMetric valueMetric_ = events.Metric.ValueMetric.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          events.Metric.ValueMetric, events.Metric.ValueMetric.Builder, events.Metric.ValueMetricOrBuilder> valueMetricBuilder_;
      /**
       * <code>optional .events.ValueMetric valueMetric = 9;</code>
       */
      public boolean hasValueMetric() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional .events.ValueMetric valueMetric = 9;</code>
       */
      public events.Metric.ValueMetric getValueMetric() {
        if (valueMetricBuilder_ == null) {
          return valueMetric_;
        } else {
          return valueMetricBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .events.ValueMetric valueMetric = 9;</code>
       */
      public Builder setValueMetric(events.Metric.ValueMetric value) {
        if (valueMetricBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          valueMetric_ = value;
          onChanged();
        } else {
          valueMetricBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .events.ValueMetric valueMetric = 9;</code>
       */
      public Builder setValueMetric(
          events.Metric.ValueMetric.Builder builderForValue) {
        if (valueMetricBuilder_ == null) {
          valueMetric_ = builderForValue.build();
          onChanged();
        } else {
          valueMetricBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .events.ValueMetric valueMetric = 9;</code>
       */
      public Builder mergeValueMetric(events.Metric.ValueMetric value) {
        if (valueMetricBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100) &&
              valueMetric_ != events.Metric.ValueMetric.getDefaultInstance()) {
            valueMetric_ =
              events.Metric.ValueMetric.newBuilder(valueMetric_).mergeFrom(value).buildPartial();
          } else {
            valueMetric_ = value;
          }
          onChanged();
        } else {
          valueMetricBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .events.ValueMetric valueMetric = 9;</code>
       */
      public Builder clearValueMetric() {
        if (valueMetricBuilder_ == null) {
          valueMetric_ = events.Metric.ValueMetric.getDefaultInstance();
          onChanged();
        } else {
          valueMetricBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      /**
       * <code>optional .events.ValueMetric valueMetric = 9;</code>
       */
      public events.Metric.ValueMetric.Builder getValueMetricBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getValueMetricFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .events.ValueMetric valueMetric = 9;</code>
       */
      public events.Metric.ValueMetricOrBuilder getValueMetricOrBuilder() {
        if (valueMetricBuilder_ != null) {
          return valueMetricBuilder_.getMessageOrBuilder();
        } else {
          return valueMetric_;
        }
      }
      /**
       * <code>optional .events.ValueMetric valueMetric = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          events.Metric.ValueMetric, events.Metric.ValueMetric.Builder, events.Metric.ValueMetricOrBuilder>
          getValueMetricFieldBuilder() {
        if (valueMetricBuilder_ == null) {
          valueMetricBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              events.Metric.ValueMetric, events.Metric.ValueMetric.Builder, events.Metric.ValueMetricOrBuilder>(
                  getValueMetric(),
                  getParentForChildren(),
                  isClean());
          valueMetric_ = null;
        }
        return valueMetricBuilder_;
      }

      private events.Metric.CounterEvent counterEvent_ = events.Metric.CounterEvent.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          events.Metric.CounterEvent, events.Metric.CounterEvent.Builder, events.Metric.CounterEventOrBuilder> counterEventBuilder_;
      /**
       * <code>optional .events.CounterEvent counterEvent = 10;</code>
       */
      public boolean hasCounterEvent() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional .events.CounterEvent counterEvent = 10;</code>
       */
      public events.Metric.CounterEvent getCounterEvent() {
        if (counterEventBuilder_ == null) {
          return counterEvent_;
        } else {
          return counterEventBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .events.CounterEvent counterEvent = 10;</code>
       */
      public Builder setCounterEvent(events.Metric.CounterEvent value) {
        if (counterEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          counterEvent_ = value;
          onChanged();
        } else {
          counterEventBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .events.CounterEvent counterEvent = 10;</code>
       */
      public Builder setCounterEvent(
          events.Metric.CounterEvent.Builder builderForValue) {
        if (counterEventBuilder_ == null) {
          counterEvent_ = builderForValue.build();
          onChanged();
        } else {
          counterEventBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .events.CounterEvent counterEvent = 10;</code>
       */
      public Builder mergeCounterEvent(events.Metric.CounterEvent value) {
        if (counterEventBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200) &&
              counterEvent_ != events.Metric.CounterEvent.getDefaultInstance()) {
            counterEvent_ =
              events.Metric.CounterEvent.newBuilder(counterEvent_).mergeFrom(value).buildPartial();
          } else {
            counterEvent_ = value;
          }
          onChanged();
        } else {
          counterEventBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .events.CounterEvent counterEvent = 10;</code>
       */
      public Builder clearCounterEvent() {
        if (counterEventBuilder_ == null) {
          counterEvent_ = events.Metric.CounterEvent.getDefaultInstance();
          onChanged();
        } else {
          counterEventBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      /**
       * <code>optional .events.CounterEvent counterEvent = 10;</code>
       */
      public events.Metric.CounterEvent.Builder getCounterEventBuilder() {
        bitField0_ |= 0x00000200;
        onChanged();
        return getCounterEventFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .events.CounterEvent counterEvent = 10;</code>
       */
      public events.Metric.CounterEventOrBuilder getCounterEventOrBuilder() {
        if (counterEventBuilder_ != null) {
          return counterEventBuilder_.getMessageOrBuilder();
        } else {
          return counterEvent_;
        }
      }
      /**
       * <code>optional .events.CounterEvent counterEvent = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          events.Metric.CounterEvent, events.Metric.CounterEvent.Builder, events.Metric.CounterEventOrBuilder>
          getCounterEventFieldBuilder() {
        if (counterEventBuilder_ == null) {
          counterEventBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              events.Metric.CounterEvent, events.Metric.CounterEvent.Builder, events.Metric.CounterEventOrBuilder>(
                  getCounterEvent(),
                  getParentForChildren(),
                  isClean());
          counterEvent_ = null;
        }
        return counterEventBuilder_;
      }

      private events.ErrorOuterClass.Error error_ = events.ErrorOuterClass.Error.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ErrorOuterClass.Error, ErrorOuterClass.Error.Builder, ErrorOuterClass.ErrorOrBuilder> errorBuilder_;
      /**
       * <code>optional .events.Error error = 11;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional .events.Error error = 11;</code>
       */
      public events.ErrorOuterClass.Error getError() {
        if (errorBuilder_ == null) {
          return error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .events.Error error = 11;</code>
       */
      public Builder setError(events.ErrorOuterClass.Error value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>optional .events.Error error = 11;</code>
       */
      public Builder setError(
          events.ErrorOuterClass.Error.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>optional .events.Error error = 11;</code>
       */
      public Builder mergeError(events.ErrorOuterClass.Error value) {
        if (errorBuilder_ == null) {
          if (((bitField0_ & 0x00000400) == 0x00000400) &&
              error_ != events.ErrorOuterClass.Error.getDefaultInstance()) {
            error_ =
              events.ErrorOuterClass.Error.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>optional .events.Error error = 11;</code>
       */
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = events.ErrorOuterClass.Error.getDefaultInstance();
          onChanged();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      /**
       * <code>optional .events.Error error = 11;</code>
       */
      public events.ErrorOuterClass.Error.Builder getErrorBuilder() {
        bitField0_ |= 0x00000400;
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .events.Error error = 11;</code>
       */
      public events.ErrorOuterClass.ErrorOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_;
        }
      }
      /**
       * <code>optional .events.Error error = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ErrorOuterClass.Error, ErrorOuterClass.Error.Builder, ErrorOuterClass.ErrorOrBuilder>
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ErrorOuterClass.Error, ErrorOuterClass.Error.Builder, ErrorOuterClass.ErrorOrBuilder>(
                  getError(),
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }

      private events.Metric.ContainerMetric containerMetric_ = events.Metric.ContainerMetric.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          events.Metric.ContainerMetric, events.Metric.ContainerMetric.Builder, events.Metric.ContainerMetricOrBuilder> containerMetricBuilder_;
      /**
       * <code>optional .events.ContainerMetric containerMetric = 12;</code>
       */
      public boolean hasContainerMetric() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional .events.ContainerMetric containerMetric = 12;</code>
       */
      public events.Metric.ContainerMetric getContainerMetric() {
        if (containerMetricBuilder_ == null) {
          return containerMetric_;
        } else {
          return containerMetricBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .events.ContainerMetric containerMetric = 12;</code>
       */
      public Builder setContainerMetric(events.Metric.ContainerMetric value) {
        if (containerMetricBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          containerMetric_ = value;
          onChanged();
        } else {
          containerMetricBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      /**
       * <code>optional .events.ContainerMetric containerMetric = 12;</code>
       */
      public Builder setContainerMetric(
          events.Metric.ContainerMetric.Builder builderForValue) {
        if (containerMetricBuilder_ == null) {
          containerMetric_ = builderForValue.build();
          onChanged();
        } else {
          containerMetricBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      /**
       * <code>optional .events.ContainerMetric containerMetric = 12;</code>
       */
      public Builder mergeContainerMetric(events.Metric.ContainerMetric value) {
        if (containerMetricBuilder_ == null) {
          if (((bitField0_ & 0x00000800) == 0x00000800) &&
              containerMetric_ != events.Metric.ContainerMetric.getDefaultInstance()) {
            containerMetric_ =
              events.Metric.ContainerMetric.newBuilder(containerMetric_).mergeFrom(value).buildPartial();
          } else {
            containerMetric_ = value;
          }
          onChanged();
        } else {
          containerMetricBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      /**
       * <code>optional .events.ContainerMetric containerMetric = 12;</code>
       */
      public Builder clearContainerMetric() {
        if (containerMetricBuilder_ == null) {
          containerMetric_ = events.Metric.ContainerMetric.getDefaultInstance();
          onChanged();
        } else {
          containerMetricBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }
      /**
       * <code>optional .events.ContainerMetric containerMetric = 12;</code>
       */
      public events.Metric.ContainerMetric.Builder getContainerMetricBuilder() {
        bitField0_ |= 0x00000800;
        onChanged();
        return getContainerMetricFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .events.ContainerMetric containerMetric = 12;</code>
       */
      public events.Metric.ContainerMetricOrBuilder getContainerMetricOrBuilder() {
        if (containerMetricBuilder_ != null) {
          return containerMetricBuilder_.getMessageOrBuilder();
        } else {
          return containerMetric_;
        }
      }
      /**
       * <code>optional .events.ContainerMetric containerMetric = 12;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          events.Metric.ContainerMetric, events.Metric.ContainerMetric.Builder, events.Metric.ContainerMetricOrBuilder>
          getContainerMetricFieldBuilder() {
        if (containerMetricBuilder_ == null) {
          containerMetricBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              events.Metric.ContainerMetric, events.Metric.ContainerMetric.Builder, events.Metric.ContainerMetricOrBuilder>(
                  getContainerMetric(),
                  getParentForChildren(),
                  isClean());
          containerMetric_ = null;
        }
        return containerMetricBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:events.Envelope)
    }

    static {
      defaultInstance = new Envelope(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:events.Envelope)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_Envelope_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_events_Envelope_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016envelope.proto\022\006events\032\017heartbeat.prot" +
      "o\032\nhttp.proto\032\tlog.proto\032\014metric.proto\032\013" +
      "error.proto\"\350\004\n\010Envelope\022\016\n\006origin\030\001 \002(\t" +
      "\022-\n\teventType\030\002 \002(\0162\032.events.Envelope.Ev" +
      "entType\022\021\n\ttimestamp\030\006 \001(\003\022$\n\theartbeat\030" +
      "\003 \001(\0132\021.events.Heartbeat\022$\n\thttpStart\030\004 " +
      "\001(\0132\021.events.HttpStart\022\"\n\010httpStop\030\005 \001(\013" +
      "2\020.events.HttpStop\022,\n\rhttpStartStop\030\007 \001(" +
      "\0132\025.events.HttpStartStop\022&\n\nlogMessage\030\010" +
      " \001(\0132\022.events.LogMessage\022(\n\013valueMetric\030",
      "\t \001(\0132\023.events.ValueMetric\022*\n\014counterEve" +
      "nt\030\n \001(\0132\024.events.CounterEvent\022\034\n\005error\030" +
      "\013 \001(\0132\r.events.Error\0220\n\017containerMetric\030" +
      "\014 \001(\0132\027.events.ContainerMetric\"\235\001\n\tEvent" +
      "Type\022\r\n\tHeartbeat\020\001\022\r\n\tHttpStart\020\002\022\014\n\010Ht" +
      "tpStop\020\003\022\021\n\rHttpStartStop\020\004\022\016\n\nLogMessag" +
      "e\020\005\022\017\n\013ValueMetric\020\006\022\020\n\014CounterEvent\020\007\022\t" +
      "\n\005Error\020\010\022\023\n\017ContainerMetric\020\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          events.HeartbeatOuterClass.getDescriptor(),
          events.Http.getDescriptor(),
          events.Log.getDescriptor(),
          events.Metric.getDescriptor(),
          events.ErrorOuterClass.getDescriptor(),
        }, assigner);
    internal_static_events_Envelope_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_events_Envelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_events_Envelope_descriptor,
        new String[] { "Origin", "EventType", "Timestamp", "Heartbeat", "HttpStart", "HttpStop", "HttpStartStop", "LogMessage", "ValueMetric", "CounterEvent", "Error", "ContainerMetric", });
    events.HeartbeatOuterClass.getDescriptor();
    events.Http.getDescriptor();
    events.Log.getDescriptor();
    events.Metric.getDescriptor();
    events.ErrorOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
